# # # # # #
# xdebug  #
# # # # # #
default['php']['xdebug']['version'] = "latest"

# XDEBUG.INI OPTIONS
default['php']['xdebug']['auto_trace'] = 1
default['php']['xdebug']['cli_color'] = 1
default['php']['xdebug']['collect_assignments'] = 1
default['php']['xdebug']['collect_includes'] = 1
default['php']['xdebug']['collect_params'] = 1
default['php']['xdebug']['collect_return'] = 1
default['php']['xdebug']['collect_vars'] = 1
default['php']['xdebug']['coverage_enable'] = 0
default['php']['xdebug']['default_enable'] = 0
default['php']['xdebug']['dump_globals'] = 1
default['php']['xdebug']['dump_undefined'] = 1
default['php']['xdebug']['extended_info'] = 1
default['php']['xdebug']['file_link_format'] = ""
default['php']['xdebug']['manual_url'] = "http://www.php.net"
default['php']['xdebug']['max_nesting_level'] = 100
default['php']['xdebug']['overload_var_dump'] = 1
default['php']['xdebug']['profiler_append'] = 0
default['php']['xdebug']['profiler_enable'] = 0
default['php']['xdebug']['profiler_enable_trigger'] = 1
default['php']['xdebug']['profiler_output_dir'] = "/tmp"
default['php']['xdebug']['profiler_output_name'] = "cachegrind.out.%p"
default['php']['xdebug']['remote_autostart'] = 0
default['php']['xdebug']['remote_connect_back'] = 0
default['php']['xdebug']['remote_cookie_expire_time'] = 3600
default['php']['xdebug']['remote_enable'] = 0
default['php']['xdebug']['remote_handler'] = "dbgp"
default['php']['xdebug']['remote_host'] = "localhost"
default['php']['xdebug']['remote_log'] = "xdebug_remote.log"
default['php']['xdebug']['remote_mode'] = "req"
default['php']['xdebug']['remote_port'] = 9000
default['php']['xdebug']['scream'] = 0
default['php']['xdebug']['show_exception_trace'] = 0
default['php']['xdebug']['show_local_vars'] = 0
default['php']['xdebug']['show_mem_delta'] = 0
default['php']['xdebug']['trace_enable_trigger'] = 1
default['php']['xdebug']['trace_format'] = 0
default['php']['xdebug']['trace_options'] = 0
default['php']['xdebug']['trace_output_dir'] = "/tmp"
default['php']['xdebug']['trace_output_name'] = "trace.%c"
default['php']['xdebug']['var_display_max_children'] = 128
default['php']['xdebug']['var_display_max_data'] = 512
default['php']['xdebug']['var_display_max_depth'] = 3