# # # # # #
# xdebug  #
# # # # # #
default['php']['xdebug']['version'] = "latest"
default['php']['xdebug']['enabled'] = false

# XDEBUG.INI OPTIONS
default['php']['xdebug']['ini']['auto_trace'] = 1
default['php']['xdebug']['ini']['cli_color'] = 1
default['php']['xdebug']['ini']['collect_assignments'] = 1
default['php']['xdebug']['ini']['collect_includes'] = 1
default['php']['xdebug']['ini']['collect_params'] = 1
default['php']['xdebug']['ini']['collect_return'] = 1
default['php']['xdebug']['ini']['collect_vars'] = 1
default['php']['xdebug']['ini']['coverage_enable'] = 0
default['php']['xdebug']['ini']['default_enable'] = 0
default['php']['xdebug']['ini']['dump_globals'] = 1
default['php']['xdebug']['ini']['dump_undefined'] = 1
default['php']['xdebug']['ini']['extended_info'] = 1
default['php']['xdebug']['ini']['file_link_format'] = ""
default['php']['xdebug']['ini']['manual_url'] = "http://www.php.net"
default['php']['xdebug']['ini']['max_nesting_level'] = 100
default['php']['xdebug']['ini']['overload_var_dump'] = 1
default['php']['xdebug']['ini']['profiler_append'] = 0
default['php']['xdebug']['ini']['profiler_enable'] = 0
default['php']['xdebug']['ini']['profiler_enable_trigger'] = 1
default['php']['xdebug']['ini']['profiler_output_dir'] = "/tmp"
default['php']['xdebug']['ini']['profiler_output_name'] = "cachegrind.out.%p"
default['php']['xdebug']['ini']['remote_autostart'] = 0
default['php']['xdebug']['ini']['remote_connect_back'] = 0
default['php']['xdebug']['ini']['remote_cookie_expire_time'] = 3600
default['php']['xdebug']['ini']['remote_enable'] = 0
default['php']['xdebug']['ini']['remote_handler'] = "dbgp"
default['php']['xdebug']['ini']['remote_host'] = "localhost"
default['php']['xdebug']['ini']['remote_log'] = "xdebug_remote.log"
default['php']['xdebug']['ini']['remote_mode'] = "req"
default['php']['xdebug']['ini']['remote_port'] = 9000
default['php']['xdebug']['ini']['scream'] = 0
default['php']['xdebug']['ini']['show_exception_trace'] = 0
default['php']['xdebug']['ini']['show_local_vars'] = 0
default['php']['xdebug']['ini']['show_mem_delta'] = 0
default['php']['xdebug']['ini']['trace_enable_trigger'] = 1
default['php']['xdebug']['ini']['trace_format'] = 0
default['php']['xdebug']['ini']['trace_options'] = 0
default['php']['xdebug']['ini']['trace_output_dir'] = "/tmp"
default['php']['xdebug']['ini']['trace_output_name'] = "trace.%c"
default['php']['xdebug']['ini']['var_display_max_children'] = 128
default['php']['xdebug']['ini']['var_display_max_data'] = 512
default['php']['xdebug']['ini']['var_display_max_depth'] = 3